TestASP/Controllers/APCreditMemoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestASP.Controllers
{
    public class APCreditMemoController : Controller
    {
        // GET: APCreditMemo
        public ActionResult APCreditMemoIndex()
        {
            return View();
        }
    }
}

TestASP/Controllers/APInvoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestASP.Controllers
{
    public class APInvoiceController : Controller
    {
        // GET: APInvoice
        public ActionResult APInvoiceIndex()
        {
            return View();
        }
    }
}

TestASP/Controllers/ARCreditMemoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestASP.Controllers
{
    public class ARCreditMemoController : Controller
    {
        // GET: ARCreditMemo
        public ActionResult ARCreditMemoIndex()
        {
            return View();
        }
    }
}

TestASP/Controllers/ARInvoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestASP.Controllers
{
    public class ARInvoiceController : Controller
    {
        // GET: ARInvoice
        public ActionResult ARInvoiceIndex()
        {
            return View();
        }
    }
}

TestASP/Controllers/AuthourizeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestASP.Controllers
{
    public class AuthourizeController : Controller
    {
        // GET: Authourize
        public ActionResult AuthourizeIndex()
        {
            return View();
        }
    }
}

TestASP/Controllers/BOMController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestASP.Controllers
{
    public class BOMController : Controller
    {
        // GET: BOM
        public ActionResult BOMIndex()
        {
            return View();
        }
    }
}

TestASP/Controllers/BPReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestASP.Controllers
{
    public class BPReportController : Controller
    {
        // GET: BPReport
        public ActionResult BPReportIndex()
        {
            return View();
        }
    }
}

TestASP/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestASP.Controllers
{
    public class CustomerController : Controller
    {
        // GET: Customer
        public ActionResult CustomerIndex()
        {
            return View();
        }
    }
}

TestASP/Controllers/DBLocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestASP.Controllers
{
    public class DBLocationController : Controller
    {
        // GET: DBLocation
        public ActionResult DBLocationIndex()
        {
            return View();
        }
    }
}

TestASP/Controllers/DeliveryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestASP.Controllers
{
    public class DeliveryController : Controller
    {
        // GET: Delivery
        public ActionResult DeliveryIndex()
        {
            return View();
        }
    }
}

TestASP/Controllers/GRPOController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestASP.Controllers
{
    public class GRPOController : Controller
    {
        // GET: GRPO
        public ActionResult GRPOIndex()
        {
            return View();
        }
    }
}

TestASP/Controllers/GoodsIssueController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestASP.Controllers
{
    public class GoodsIssueController : Controller
    {
        // GET: GoodsIssue
        public ActionResult GoodsIssueIndex()
        {
            return View();
        }
    }
}

TestASP/Controllers/ITMController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestASP.Controllers
{
    public class ITMController : Controller
    {
        // GET: ITM
        public ActionResult ITMIndex()
        {
            return View();
        }
    }
}

TestASP/Controllers/IncomingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestASP.Controllers
{
    public class IncomingController : Controller
    {
        // GET: Incoming
        public ActionResult IncomingIndex()
        {
            return View();
        }
    }
}

TestASP/Controllers/LogInController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestASP.Controllers
{
    public class LogInController : Controller
    {
        // GET: LogIn
        public ActionResult LogInIndex()
        {
            return View();
        }
    }
}

TestASP/Controllers/OutgoingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestASP.Controllers
{
    public class OutgoingController : Controller
    {
        // GET: Outgoing
        public ActionResult OutgoingIndex()
        {
            return View();
        }
    }
}

TestASP/Controllers/SalesOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestASP.Controllers
{
    public class SalesOrderController : Controller
    {
        // GET: SalesOrder
        public ActionResult SalesOrderIndex()
        {
            return View();
        }
    }
}

TestASP/Controllers/SalesReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestASP.Controllers
{
    public class SalesReportController : Controller
    {
        // GET: SalesReport
        public ActionResult SalesReportIndex()
        {
            return View();
        }
    }
}

TestASP/Controllers/TransferController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestASP.Controllers
{
    public class TransferController : Controller
    {
        // GET: Transfer
        public ActionResult TransferIndex()
        {
            return View();
        }
    }
}

TestASP/Controllers/UserControlController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestASP.Controllers
{
    public class UserControlController : Controller
    {
        // GET: UserControl
        public ActionResult UserControlIndex()
        {
            return View();
        }
    }
}

TestASP/Controllers/WelcomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestASP.Controllers
{
    public class WelcomeController : Controller
    {
        // GET: Welcome
        public ActionResult WelcomeIndex()
        {
            return View();
        }
    }
}

TestASP/Views/APCreditMemo/APCreditMemoIndex.cshtml
@{
    ViewBag.Title = "APCreditMemoIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";

    <script>
        $(document).ready(function () {

        });
    </script>
    <style>
    </style>
}

<body>
    @*Customer List*@
    <div class="modal fade" id="customerlist" role="dialog">
        <div class="modal-dialog modal-lg" id="dvmodal">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Vender Information</h4>
                </div>
                <div class="modal-body" style="height:500px;overflow:auto;padding-top:2px;">
                    <table class="table table-hover" style="font-size:11px;" id="tblcustomer">
                        <tr style="height:40px;">
                            <td style="border:none;">Find</td>
                            <td colspan="4" style="border:none;"><input type="text" id="txtfindcustomer" style="width:100%" /></td>
                        </tr>
                        <tr>
                            <th style="text-align: center; width: 5%; background-color: #e6e6ff; border:1px solid silver;">#</th>
                            <th style="text-align: center; width: 15%; background-color: #e6e6ff; border: 1px solid silver;">Vender Code</th>
                            <th style="text-align: center; width: 55%; background-color: #e6e6ff; border: 1px solid silver;">Vender Name</th>
                        </tr>
                        <tr>
                            <th style="text-align: center;height:21px; border:1px solid silver;">1</th>
                            <th style="text-align: center;height:21px; border:1px solid silver"></th>
                            <th style="text-align: center;height:21px; border:1px solid silver"></th>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="styleContact">
        <div class="styleSubContact">
            <div class="styleHeader">
                <h5 style="padding-top:5px;padding-left:5px;">A/P Credit Memo</h5>
            </div>
            @*Document Header*@
            <div class="styleMain">
                <div style="width:50%;height:115px;background-color:none;padding-top:10px;padding-left:10px;float:left;">
                    <table class="tablenoborder table-hover;">
                        <tr>
                            <td><label style="width:130px;padding-left:20px;padding-top:5px">Customer</label></td>
                            <td>
                                <input type="text" id="txtNumber" name="BPMasterData.Number" style="width:390px;" />
                            </td>
                            <td style='float:right;padding-top:3px'><img src='../Image/customer.png' id="customer" style='width:20px;height:20px;cursor:pointer' name='customer' data-toggle="modal" data-target="#customerlist" /></td>
                        </tr>
                        <tr>
                            <td><label style="width:130px;padding-left:20px;padding-top:5px">Name</label></td>
                            <td>
                                <input type="text" id="txtNumber" name="BPMasterData.Number" style="width:390px;" />
                            </td>
                        </tr>
                        <tr>
                            <td><label style="padding-left:20px;width:130px;padding-top:5px">Doc Ref.</label></td>
                            <td><input type="text" id="txtDocRef" value="" name="GoodsReceipt.DocRef" style="width:390px" /> </td>
                        </tr>
                    </table>
                </div>
                <div style="width:48%;height:120px;background-color:none;padding-top:10px;padding-left:22px;float:left;">
                    <table>
                        <tr>
                            <td><label style="padding-left:20px;width:130px;padding-top:5px">Doc. No.</label></td>
                            <td><input type="text" id="txtTaxDate" data-provide="datepicker" value="" name="GoodsReceipt.TaxDate" style="width:390px" onclick="onchange()" /> </td>
                        </tr>
                        <tr>
                            <td><label style="padding-left:20px;width:130px;padding-top:5px">Status</label></td>
                            <td><input type="text" id="txtDocRef" value="" name="GoodsReceipt.DocRef" style="width:390px" /> </td>
                        </tr>
                        <tr>
                            <td><label style="padding-left:20px;width:130px;padding-top:5px">Posting Date</label></td>
                            <td><input type="text" id="txtDocDate" data-provide="datepicker" value="" name="GoodsReceipt.DocDate" style="width:390px" /> </td>
                        </tr>
                        <tr>
                            <td><label style="padding-left:20px ;width:130px;padding-top:5px">Document Date</label></td>
                            <td><input type="text" id="txtTaxDate" data-provide="datepicker" value="" name="GoodsReceipt.TaxDate" style="width:390px" onclick="onchange()" /> </td>
                        </tr>
                        @*<tr style="height:20px"></tr>*@
                    </table>
                </div>
                <div style="width:100%;height:200px;background-color:WhiteSmoke;padding-left:30px;overflow:auto;">
                    <div>
                        <h5 style="padding-left:0px;font-size:16px;">Contents</h5>
                    </div>
                    <div style="padding-top:1px;width:98%;height:160px;border:1px solid silver;padding-left:1px">
                        <table class="table table-hover" style="font-size:11px;height:20px;width:100%;" id="tblcustomer">
                            <tr>
                                <th style="text-align: center; width: 3%;  background-color: #e6e6ff; border:1px solid silver;">#</th>
                                <th style="text-align: center; width: 10%; background-color: #e6e6ff; border: 1px solid silver;">Item Code</th>
                                <th style="text-align: center; width: 30%; background-color: #e6e6ff; border: 1px solid silver;">Description</th>
                                <th style="text-align: center; width: 7%; background-color: #e6e6ff; border: 1px solid silver;">Quantity</th>
                                <th style="text-align: center; width: 9%; background-color: #e6e6ff; border: 1px solid silver;">Price</th>
                                <th style="text-align: center; width: 9%; background-color: #e6e6ff; border: 1px solid silver;">Line Total</th>
                                <th style="text-align: center; width: 10%; background-color: #e6e6ff; border: 1px solid silver;">Warehouse</th>
                                <th style="text-align: center; width: 15%; background-color: #e6e6ff; border: 1px solid silver;">Remark</th>
                            </tr>
                        </table>
                    </div>
                </div>
                <div style="width:50%;height:120px;background-color:none;padding-top:1px;padding-left:4px;float:left;">
                    <table class="tablenoborder table-hover;">
                        <tr>
                            <td><label style="padding-left:30px;width:130px;padding-top:5px">Sale Employee</label></td>
                            <td>
                                <select id="cboGroup" name="BPMasterData.Group" style="height:24px ;width:380px">
                                    <option value="BP_Employee"></option>
                                    <option value="BP_Government">None</option>
                                </select>
                            </td>
                        </tr>
                        <tr style="height:50px"></tr>
                        <tr>
                            <td><label style="width:150px;padding-left:30px;padding-top:0px">Remark</label></td>
                            <td colspan="2">
                                <textarea id="remark" rows="4" style="width:380px;resize:none;border:1px solid silver;"></textarea>
                            </td>
                        </tr>
                    </table>
                </div>
                <div style="width:48%;height:120px;background-color:none;padding-top:1px;padding-left:110px;float:left;">
                    <table>
                        <tr>
                            <td><label style="padding-left:50%;width:250px;padding-top:5px">Total Before Dis.</label></td>
                            <td><input type="text" id="txtDocDate" data-provide="datepicker" value="" name="GoodsReceipt.DocDate" style="width:185px;" disabled /> </td>
                        </tr>
                        <tr>
                            <td><label style="padding-left:50%;width:250px;padding-top:5px">Discount</label></td>
                            <td><input type="text" id="txtDocDate" data-provide="datepicker" value="" name="GoodsReceipt.DocDate" style="width:185px" /> </td>
                        </tr>
                        <tr>
                            <td><label style="padding-left:50%;width:250px;padding-top:5px">Tax</label></td>
                            <td><input type="text" id="txtDocDate" data-provide="datepicker" value="" name="GoodsReceipt.DocDate" style="width:185px" /> </td>
                        </tr>
                        <tr>
                            <td><label style="padding-left:50%;width:250px;padding-top:5px">Grand Total</label></td>
                            <td><input type="text" id="txtDocDate" data-provide="datepicker" value="" name="GoodsReceipt.DocDate" style="width:185px" disabled /> </td>
                        </tr>
                        <tr>
                            <td><label style="padding-left:50%;width:250px;padding-top:5px">Applied Amount</label></td>
                            <td><input type="text" id="txtDocDate" data-provide="datepicker" value="" name="GoodsReceipt.DocDate" style="width:185px" disabled /> </td>
                        </tr>
                        <tr>
                            <td><label style="padding-left:50%;width:250px;padding-top:5px">Balance Due</label></td>
                            <td><input type="text" id="txtDocDate" data-provide="datepicker" value="" name="GoodsReceipt.DocDate" style="width:185px" disabled /> </td>
                        </tr>
                    </table>
                </div>
            </div>
            @*Control Buttons*@
            <div class="styleBarButtom">
                <div style="padding-top:0px;padding-left:20px;width:100%">
                    <table class="tablenoborder table-hover" style="width:100%;">
                        <tr>
                            <td style="text-align:left;width:2%;"></td>
                            <td style="text-align:left;width:8%;"><input type="button" id="btnAdd" value="Add" style="width:80px;height:25px;border:1px solid Teal; border-radius:5px;background-color:NavajoWhite" /></td>
                            <td style="text-align:left;width:2%"></td>
                            <td style="text-align:left;width:8%"><input type="button" id="btnCancel" value="Cancal" style="width:80px;height:25px;border:1px solid Teal; border-radius:5px;background-color:NavajoWhite" /></td>
                            <td style="text-align:left;width:2%"></td>
                            <td style="text-align:left;width:8%"><input type="button" id="btnFind" value="Find" style="width:80px;height:25px;border:1px solid Teal; border-radius:5px;background-color:NavajoWhite" /></td>
                            <td style="text-align:left;width:70%"></td>
                            <td style="padding-right:25px">
                                <select id="cboGroup" name="BPMasterData.Group" style="height:24px ;width:120px; background-color:Beige " disabled>
                                    <option value="BP_Employee">Copy From</option>
                                    <option value="BP_Government">None</option>
                                </select>
                            </td>
                            <td style="padding-right:40px">
                                <select id="cboGroup" name="BPMasterData.Group" style="height:24px ;width:120px; background-color:Beige" disabled>
                                    <option value="BP_Employee">Copy To</option>
                                    <option value="BP_Government">None</option>
                                </select>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</body>

TestASP/Views/LogIn/LogInIndex.cshtml
@{
    ViewBag.Title = "LogInIndex";
    Layout = null;
    @Scripts.Render("~/Scripts/jquery-1.11.0.min.js")
    @Styles.Render("~/Content/font-awesome.css")
    @Styles.Render("~/Content/font-awesome.min.css")
    @Styles.Render("~/Content/css.css")
    @Styles.Render("~/Content/bootstrap.min.css")
    <script>
        $(document).ready(function () {
            $("#btnOk").click(function () {
                var baseUrl="@Url.Action("WelcomeIndex", "Welcome")";
                window.location.href = baseUrl;
            });
        });
        function exitWindows() {
            alert("Hi");
        }
    </script>
    <style>
        .LogInWindows {
            width: 40%;
            height: 400px;
            border: 0px solid black;
            background-color: none;
            margin-top: 6%;
            text-align: left;
            text-decoration-style:solid;

        }

        .BarTitle {
            width: 100%;
            height: 24px;
            border-bottom: 1px solid black;
            background-color: gainsboro;
            text-align: left;
            
        }

        .tilteWindows {
            width: 94%;
            height: 24px;
            text-align: left;
            padding-top: 3px;
            padding-left: 2px;
            font-size: 13px;
            float: left;
        }

        .exitIcon {
            width: 5%;
            height: 24px;
            float: left;
        }

        .contactWin {
            width: 100%;
            height: 90%;
            border-bottom: 0px solid black;
            background-color:whitesmoke;
            text-align: left;
            border-radius:6px;
        }
    </style>
}
<body style="background-color:#026179;">
    <center>
        <div class="LogInWindows">
            <div class="BarTitle">
                <div class="tilteWindows">
                    Choose Database
                </div>
                <div class="exitIcon" style="padding-right:1px"><img src="../Image/exit_Login.png" style="width:24px;height:24px;cursor:pointer;" onclick="exitWindows()"></div>
            </div>
            <div class="contactWin">
                <div style="padding-left:23px;padding-top:20px;">
                    The list of Database
                </div>
                <center>
                    <div style="width:90%;height:200px;background-color:none;margin-top:5px;border:1px solid silver;">
                        <table class="tablenoborder table-hover;" style="width:100%;">@*style="font-size:13px;width:100%;border:1px solid midnightblue;border-collapse: collapse;" id="tblDatabaseName">*@
                            <thead>
                                <tr>
                                    <th style="text-align: center; width: 50%;height:20px;border:1px solid silver;background-color:none;font-size:14px;">Company Name</th>
                                    <th style="text-align: center; width: 50%;height:20px;border:1px solid silver;background-color:none;font-size:14px;">Database Name</th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </center>
                <div style="width:98%;padding-top:10px;">
                    <table style="font-size:13px;width:108%;">
                        <tr>
                            <td style="text-align:left;width:100%;padding-left:30px;padding-top:3px;">
                                <label style="width:100px">Username</label>
                                <input type="text" id="txtUsername" style="width:70%;" maxlength="15" />
                            </td>
                        </tr>
                        <tr>
                            <td style="text-align:left;width:100%;padding-left:30px;padding-top:3px;">
                                <label style="width:100px">Password</label>
                                <input type="password" id="txtUsername" style="width:70%;" maxlength="8" />
                            </td>
                        </tr>
                    </table>
                </div>
                <div style="width:40%;padding-top:10px;padding-right:10px;margin-left:340px;">
                    <table style="font-size:13px;width:100%;">
                        <tr>
                            <td style="width:30%; padding-left:30px"><input type="button" value="Ok" id="btnOk" style="width:80%; background-color:NavajoWhite" /></td>
                            <td style="width:30%"><input type="button" value="Cancel" id="btnCancel" style="width:60%;background-color:NavajoWhite" /></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </center>
</body>